---
version: '2'
services:
  db:
    container_name: gentle_panther_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --max-allowed-packet=128M
    networks:
      - default

  drupal:
    container_name: gentle_panther_web
    depends_on:
      - db
    image: reg.hcpss.org/gentle_panther/web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8091:80
    volumes:
      - ./drupal:/var/www/drupal
      - ./.credentials:/srv/credentials
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      DRUPAL_ENV: test
    networks:
      default:
        aliases:
          - stopbullying.hcpss.localhost
    command: >
      bash -c "drush --root=/var/www/drupal/web si -y --existing-config --account-pass=admin
      && drush --root=/var/www/drupal/web gentle-panther:init
      && drupal node:access:rebuild
      && /usr/sbin/apache2ctl -D FOREGROUND"

  chrome:
    container_name: chrome
    image: selenium/standalone-chrome:3.141.59-radium
    shm_size: 2gb
    networks:
      - default

  firefox:
    container_name: firefox
    image: selenium/standalone-firefox:3.141.59-radium
    shm_size: 2gb
    networks:
      - default

  selenium:
    container_name: selenium
    image: reg.hcpss.org/mpia/selemium
    build: ./docker/selenium
    volumes:
      - ./docker/selenium/app:/app
    command: tail -f /dev/null
    networks:
      - default

networks:
  default: