---
version: '2'
services:
  db:
    container_name: stopbullying_db
    image: mysql:5.7
    volumes:
      #- ./drupal.sql:/docker-entrypoint-initdb.d/drupal.sql
      - ./.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --max-allowed-packet=128M
  drupal:
    container_name: stopbullying_web
    depends_on:
      - db
    image: reg.hcpss.org/stopbullying/web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8091:80
    volumes:
      - ./drupal:/var/www/drupal
      - ./.credentials:/srv/credentials
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      DRUPAL_ENV: dev
    # command: >
    #   bash -c "drush --root=/var/www/drupal/web upwd admin admin
    #   && /usr/sbin/apache2ctl -D FOREGROUND"

  python:
    image: python
    links:
      - drupal:stopbullying.hcpss.localhost
    volumes:
      - ./app.py:/app.py
    command: bash -c "pip install requests && tail -f /dev/null"
