---
version: '2'
services:
  db:
    container_name: gentle_panther_db
    image: mysql:5.7
    volumes:
      - ./.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --max-allowed-packet=128M

  drupal:
    container_name: gentle_panther_web
    depends_on:
      - db
    image: reg.hcpss.org/gentle_panther/web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8091:80
    volumes:
      - ./drupal:/var/www/drupal
      - ./.credentials:/srv/credentials
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      DRUPAL_ENV: dev
